### ISSUE TITLE
Please install assets correctly to comply with FHS

### ISSUE THREAD

**Issue by viccuad** [moddevices/modguis#1]
Hi,

As talked on [Guitarix's mailing list](https://sourceforge.net/p/guitarix/mailman/guitarix-developer/thread/56E70598.5070509@viccuad.me/#msg34934732):

The current Guitarix v0.34, which is shipping the modgui plugin bundle, installs png files on `/usr/lib`. According to the Filesystem Hierarchy Standard (`man hier` in your system), architecture-independent files such as this should be installed in `/usr/share` instead.

```
    usr/lib/lv2/gx_amp.lv2/modgui/knobs/chicken-head/_strip.png
    usr/lib/lv2/gx_amp.lv2/modgui/knobs/chicken-head/_strip.png
    usr/lib/lv2/gx_amp.lv2/modgui/racks/model-001/model-001.png
    usr/lib/lv2/gx_amp.lv2/modgui/racks/model-001/model-001.png
    usr/lib/lv2/gx_amp.lv2/modgui/screenshot-gxamplifier-x.png
    usr/lib/lv2/gx_amp.lv2/modgui/screenshot-gxamplifier-x.png
    usr/lib/lv2/gx_amp.lv2/modgui/switches/switch-001.png
    usr/lib/lv2/gx_amp.lv2/modgui/switches/switch-001.png
    usr/lib/lv2/gx_amp.lv2/modgui/thumbnail-gxamplifier-x.png
    usr/lib/lv2/gx_amp.lv2/modgui/thumbnail-gxamplifier-x.png
    usr/lib/lv2/gx_amp.lv2/modgui/utils/dropdown-arrow-white.png
    usr/lib/lv2/gx_amp.lv2/modgui/utils/dropdown-arrow-white.png
```

Cheers.

**Comment by falkTX** [comment]
this is literally impossible.

in mod we _require_ bundles to be self-contained.
the entire OS does not have resources regarding the modguis, and this is intentional.

there are no jack standalones on MOD, everything is done by lv2 plugins.
as such, plugins cannot and will not depend on resources installed outside of their bundle.
this is by design and will not change.

**Comment by viccuad** [comment]
> in mod we require bundles to be self-contained.

It can perfectly continue to be self contained bundle, but with assets on /usr/share.

> there are no jack standalones on MOD, everything is done by lv2 plugins.

And LV2 plugins perfectly allow for putting assets on `/usr/share`. For example, look at [Guitarix's](https://packages.debian.org/sid/amd64/guitarix/filelist) installed files, you will find assets where they correspond: `/usr/share/gx_head/skins/LV2/Ampeg-GVT15H.png`. There are many other examples of LV2 plugins that install assets where it corresponds.

> this is literally impossible.

I have just show it isn't (and I suspect you already knew, since you are a LV2 plugin developer yourself).

> this is by design and will not change.

I have just read your kickstarter campaign and while you don't mention nor promise to give back to the FOSS and Linux community from which you use the OS and audio plugins, it would be nice if your project would do the correct technical thing, and also give back to the community, which allows everyone to have a sane ecosystem that everyone can trust and build on top of (such as the MOD developers).

Are you open to reconsider your stance?

Cheers.

**Comment by odurc** [comment]
Hey @viccuad. I'm wondering if you need MOD files for your use case. If don't, a good solution would be create a flag in guitarix wscript file which enable/disable MOD files installing.

**Comment by viccuad** [comment]
> Hey @viccuad. I'm wondering if you need MOD files for your use case. If don't, a good solution would be create a flag in guitarix wscript file which enable/disable MOD files installing.

It is a solution, but not the best. If the MOD team doesn't want to tackle this to improve the quality of their software, I guess that is what will need to be done.

Sadly, that probably would make this topic appear on each and every free software project that implements the MOD SDK and modgui that the MOD team works on top of, putting more work on those developers (which normally do their job without remuneration also), and leaving them less time to improve their effects so MOD devices can enjoy them.

So, as I said, are you open to reconsider your stance?

**Comment by falkTX** [comment]
I guess I should have written a more in-depth explanation since you're new to MOD, sorry.

The MOD is not a PC, and it does not intend to be one.
The root filesystem is read-only and intended to be static, with only the 'user' dir having write permission.

Now as I said, because we're only interested on plugins (installed at ~/.lv2/) we strip everything else when building them.
The installed plugins are managed through our own "plugin store", where the user can install, remove and upgrade plugins.
Because of this fact, we simply don't install shared plugin resources on the root filesystem.
If we did, the plugins might be dependent on OS versions. This is the important part.
With shared resources plugins would require OS updates to run, and old plugins might break when we update the OS without updating them too.
This tying up of OS to plugin versions is a problem we do not want to deal with.

We did used to have shared resources before though...
And it was a pain to deal with regarding updates.
If a single plugin required 1 small GUI fix, the entire resources had to be updated.
Some changes made to the shared resources unintentionally broke plugins.

Now that we have all plugins self-contained those issues do not happen.
The shared resources were imported into our SDK and are copied to the generated MODGUIs, ready to be used on any MOD.
The OS can be updated and downgraded without affecting plugin design, and plugin themselves can also be updated without worries.

**Comment by viccuad** [comment]
> Now as I said, because we're only interested on plugins (installed at ~/.lv2/) we strip everything else when building them.

All I am saying keeps being perfectly consistent with installing your needed plugins at `~/.lv2/` You only need to keep the architecture-dependent and architecture-independent files separated in their own directories instead of just in one directory, and all of that inside of `~/.lv2/…`.

> Because of this fact, we simply don't install shared plugin resources on the root filesystem.

Notice that I'm not advocating for you to do that. 

Right now you make projects, such as Guitarix, implement your SDK. Once those projects have the modgui added, you could just substitute the configure prefix from `configure --prefix=/usr` to `configure --prefix=/home/mod/.lv2` and it will work the same as you want it now: it will install at `~`, the write enabled part of your filesystem. And that would make guitarix have the same file tree inside that folder. 

Please remember that these projects not only exist for the MOD team benefit of being included in your device, they have been around for years, and keep being used in other ecosystems such as Debian/Fedora/etc, where they need to do things correctly. 

Lets think on what would happen to that OS you are using as a base of your product if every developer acted the same way as you propose: it would morph from the stable and well regarded system it is now, to a pulp. I wonder if the MOD team would then use it as their base.

In case you didn't want to just change the prefix flag on the projects you use, as everyone else does for packaging them for distros (and since you yourself package software for your KXstudio repos, I suppose you already know) and has been the way to do this for 2 decades, you could for example go the [systemd way](http://0pointer.net/blog/projects/stateless.html) of embedded devices.

Frankly, this conversation shows to me that you are willing to put obstacles for everyone, in fear of competition. Which is fine, and you are free to do, but please don't pose it as technical reasons.

**Comment by falkTX** [comment]
Don't get us wrong please.
We don't want to put obstacles or anything like that, we want things to work for the system we build.
Our target is obviously the "MOD OS", regular distros are a 2nd thought.
We're a very small team, I don't think it would make sense for this to be any other way.
Being somewhat a packager myself, I try my best to keep the MOD software easy to package.

Anyway..

If we put files outside of lv2 bundles we'll need to keep track of which files belong to which bundles.
(as need to ensure plugins never conflict with each other when updated or removed)
This also means we would need 2 folders per plugin - 1 for resources and another for plugin DSP.
If the DSP and GUI share some files (say some pre-generated configs), those files would have to be duplicated.
The plugin store would have to keep track of this (probably by reusing the same basename for resources and lv2 bundle, or maybe using a symlink).
What happens if the user renames one of them, how can the store keep track of which resource belongs to which plugin?
Symlinks are no good either, as renaming their target breaks them.

Note that I'm not against the idea itself, but we're not going to do it ourselves.
In the guitarix case the modguis can be installed on some shared location and then symlinked in the lv2 bundle.
That's fine for linux desktops, but certainly not for MOD.

Another thing to note is that the "MOD OS" does not include any plugins, or plugin related resources.
The only thing you will find in /usr/lib/lv2 are the LV2 specs. :)
When the plugins are built, the cloud grabs only the lv2 bundle (which is the only thing we need) and packs them for later download when requested.
Users install plugins by downloading them from the store, which brings that packed lv2 bundle and nothing else.
So the 'prefix' is meaningless.

Anyway, I don't understand why you have to be so picky about this.
MOD is certainly not the only that has images or similar resources inside LV2 bundles.
(Note that lv2 ttl files are also architecture independent files, should those not be in /usr/lib too?)

You're also imposing linux distro specific rules into the LV2 world.
LV2 is not just for linux, it's cross-platform.
Let's take an example of an LV2 plugin for Windows, where the UI graphics are PNG files.
Is there any reason the plugin developer needs to install the PNG files outside the LV2 bundle?
The LV2 API is very nice for developers by passing the plugin/UI bundle folder as an instantiate parameter. Developers use that to easily access required files, they no longer need to be limited to compile-time hardcoded locations.
This is one of the things that makes LV2 great, the plugin bundles can be self-contained and made to run on any machine regardless of external files.
When the bundle is properly made, users can move it from pc to pc and to any random folder and it will still work.
We can't do that with LADSPA or VST that need external data. Since they are single binaries the users have to be careful to move required resources together with the binary.

I make use of this feature for my public builds of Carla LV2 plugin.
Even though the build tarball I release has a standalone, I duplicate the files on the LV2 bundle.
The user can grab just the lv2 bundle and put it into ~/.lv2/ without caring about the standalone or extra resources. Everything needed to run is just there.

**Comment by falkTX** [comment]
Speaking about resources on lv2 bundles, here's something...

First example:

```
$ dpkg -L invada-studio-plugins-lv2  | grep png | grep logo
/usr/lib/lv2/invada.lv2/gtk/invada_logo.png
```

Another one:

```
$ dpkg -L abgate | grep png | grep background
/usr/lib/lv2/abGate.lv2/background.png
```

Those packages are available on Debian right now.

Why do these developers put their resource files inside the lv2 bundle?
Because it's much easier to do so, and it actually makes sense considering the LV2 API.

You're forcing linux distributions specific rules into LV2.
The fact is - LV2 plugins are much more than just binaries.
The non-binary data _plus_ the binary is (usually) what makes an LV2 bundle.
Some plugins (like ingen "instruments") do not actually contain any binaries.
I seriously hope you don't consider putting that into /usr/share/...

**Comment by brummer10** [comment]
Hi

So I've added a configure switch to disable the installation of the MOD GUI stuff from guitarix.
The remaining issue is, that I would love to see the MOD app in debian, which, will then pop up the very same situation again. That's a pity. 
I'm pretty sure that this could be solved, but I understand that you guy's have other priority’s for now. I'll hope that you sooner or later find a way to handle this stuff in accordance with the Filesystem Hierarchy Standard.

**Comment by falkTX** [comment]
well, speaking for myself, I hope distros reconsider their position.
they're forcing some specific rules into every LV2 developer if they want to see their plugins packaged.

take the example of abgate and invada, where the software is only LV2 plugins without standalones.
they will have to modify the current install procedure to be compliant with FHS, even though the current setup already works fine.
lv2filter (now abandoned) used to have just 2 image files. does it make sense to create a new dir in /usr/share just for that?
the files are going to be symlinked afterwards, so the png reference will still be there in /usr/lib.

and please don't forget that this breaks user experience, because with a shared resource folder for lv2 stuff the user can no longer grab plugins from /usr/lib/lv2/ to a friend and expect it to work.

my point is - this FHS requirement should not be imposed on upstream developers.
instead, **distributions are the ones that should do it** (in case they care anyway).
not all distros have this strict requirement, and non-linux platforms are better off with resources inside the bundle.

**Comment by brummer10** [comment]
The FHS exist to keep Linux systems clean and consistent over distro boarders, for me, it make sense to follow this standard. 

However, to your example, there is absolutely no need to do a symlink, a simple define flag, build during configure will do the job.  At least, that is how I do it. Adding a folder in /usr/share, will happen on most distros anyway, that's where the documentation goes, . .

I also think it is a bad idea to move binary’s, or in this case bundles around from on system to a other, by hand copy. We use scripts and package managers for that task, and again, they exist to keep your system clean. Maintaining a system were bundles and binary’s been moved around from elsewhere, could become a nightmare soon, and remains me on the usual windows way to handle this stuff.

I also don't think that we should leave the task of careful installation to distro packagers, this should be included in upstream. Configure flags could do magic thinks, as you properly know. 

But, don't get me wrong, I'm fine with the MOD and you are free to handle stuff like you wish, even inside guitarix, you are welcome to commit your stuff. I'll do my very best to support you, and keep track with the need of the distribution maintainers.

**Comment by falkTX** [comment]
ok, we just disagree on some points of view then.

for me, I prefer to get everything inside the lv2 bundles as that allows _me_ to release public builds of my plugins and they will work on any computer.
to be able to support that and FHS, I'll have to code the plugins so that they can work both ways.
that's a little work from which I have no personal gain, and will require me to do extra testing each release.

now support with modguis is a bit tricky.
this is the definition of a modgui:

```
<http://distrho.sf.net/plugins/Nekobi>
    modgui:gui [
        modgui:resourcesDirectory <modgui>;
        modgui:iconTemplate <modgui/icon-nekobi.html>;
        modgui:stylesheet <modgui/stylesheet-nekobi.css>;
        modgui:screenshot <modgui/screenshot-nekobi.png>;
        modgui:thumbnail <modgui/thumb-nekobi.png>;
    ].
```

the modgui folder being inside the lv2 bundle makes it possible to use this as-is.
the relative path works nicely. a symlink would work too.

if we'd go for putting the modgui in some other directory without a symlink, those paths would need to change to something hardcoded.
we don't have a defined spec on where those should go though. plus the MOD OS has the root fs as read-only, so the modguis would endup in /root/modguis/... which I bet is not a good path for FHS either.

**Comment by brummer10** [comment]
I didn't know which build environment you are using, but, a simple solution could be to use a modgui.ttl.in file and substitute the path during configure. That should work for the needs of the MOD, (there will nothing change for the MOD this way), and, on Top of it, any distributor is free to set the path according to there needs.

True is, the path maybe then hard-coded on the distributed bundles, and moving bundles from on system to a other will fail, but, as I pointed out, this should be discouraged any way, I think, providing a script to do this is much more comfortable and save.

**Comment by falkTX** [comment]
that might be an option, but it's not something we can spend time on right now.
we already have some Duo units out there...
we'll pick up this conversation again in some months.

still, personally, I prefer when the bundles have everything included inside.
it makes things much easier to manage as a user.

**Comment by x42** [comment]
> It can perfectly continue to be self contained bundle, but with assets on /usr/share.

Uhm what?  it can be all green but be have some red stuff over there..  :)

I don't know why you're discussing this at all. http://lv2plug.in/pages/filesystem-hierarchy-standard.html is perfectly clear on this.

**Comment by falkTX** [comment]
Indeed, I should have checked that first.

> LV2 bundles are self-contained and may contain any kind of data (binary, text, executable, system-specific, portable, etc.). These different kinds of data are not installed to separate paths as in the traditional Unix FHS

**Comment by x42** [comment]
if you're interested in a precedent:  The debian package of setBfree  solves this by duplicating the relevant resources.   The jack app deploys to `/usr/bin`,   additional data to `/usr/share`
the LV2 plugin includes all UI data directly in the binary (and is completely relocatable, not depending on any external resources).

It took me while to explain this to the debian ftp-masters back in the day, but they eventually agreed that pro audio is sufficient niche to warrant this.

Edit: 
PS. How much data is it anyway that would have to be duplicated (shipped both inside the bundle(s) and outside) to make both worlds happy?

PS. You may argue that the LV2 FHS is crap etc etc, but as was pointed out via `man hier`, breaking an established standard is really not the way to go.

**Comment by brummer10** [comment]
>  the LV2 plugin includes all UI data directly in the binary (and is completely relocatable, not depending on any external resources).

We do it for our library’s (libgxw/libgxwmm) as well, but, that shouldn't work for stuff like the MOD GUI's.
And as you point out yourself, you do some extra work, to hide the fact, that you install images into /usr/lib in order to fill the requirements of the FHS. 
This, looks to me as you are not really happy with the antithetical definition of the LV2 bundle versus FHS. 
Should we now all compile our images into the binary's to fill both needs? I don't think that is a good solution.

**Comment by brummer10** [comment]
and, forgot to mention, toolkit library's, should they be included into the bundle? 
(just a joke, I'm duck and run)

**Comment by falkTX** [comment]
I also build images into binary data together with the plugin UI sometimes.
I do that because of VST not having a definition of a bundle, and I want my plugins to be self-contained.
The process is brought to LV2 because the base code is the same..

@brummer10 on my DPF plugins (and I guess setBfree too), the images being part of the binary is also because it makes sending them to openGL much easier.
this means not having to find files, open them, allocate memory for them, and then closing them.
the data is always available as it's compiled in.

also, good thing you mention toolkit libraries.
On Windows and OSX we do indeed ship those libraries together with the plugins. ;)

**Comment by x42** [comment]
Resources do not have to be embedded in the binary. The LV2 spec only requires them to be inside the bundle folder.

@brummer10 : In my case, yes the complete toolkit (here robtk) is included as well. That is a prerequisite for portable LV2s (OSX, Windows, Linux, BSD). The plugin is completely self contained.

**Comment by brummer10** [comment]
> Resources do not have to be embedded in the binary. The LV2 spec only requires them to be inside the bundle folder.

Yes, but the FHS requires that Images not been installed in /usr/lib, so to fulfill both requirements,  . . . 
On the other hand, a developer needs to make a decision which specs to contradict. 
That is, a sad situation.

**Comment by falkTX** [comment]
I believe the LV2 spec should take precedence over the FHS one.

**Comment by x42** [comment]
It's not an _image_. Its a resource needed for a LV2 plugin (which just so happens to be an image).

From the FHS point of view however it is a LV2 plugin resource and hence belongs with the plugin and not in /usr/share

**Comment by brummer10** [comment]
Okay, I do a check, for png files installed on my debian/sid system in /usr/lib, and, . . 
it's a impressive list:  http://pastebin.com/9uW8yq2r
In short, there are 325 png files installed, were only one is related to LV2. 
/lv2/invada.lv2/gtk/invada_logo.png

most image files comes from libreoffice, python and ruby.

**Comment by drobilla** [comment]
Bundles must be self-contained.  That's the entire point of them.  This is the only sane/portable way for resources to be available to plugins.  The bundle path is available at run-time, and is used to retrieve whatever resources are shipped with the plugin.

Plugins definitely should not be spreading things all over the file system and have OS-dependent hard-coded paths baked into their code.  There is no debate about that.

LV2 is far from the only thing that works this way, and since the FHS doesn't have a location specifically for such things, $PREFIX/lib is the conventional place for them, as brummer10 noted above.

Anyway, by my reading, the FHS does not "require" any such thing.  There are very good technical reasons why LV2 bundles are self-contained.  I see no good technical reasons that actually occur in practice which would justify violating the spec.

If if makes you feel any better, consider the LV2 bundles (which, being self-contained, are atomic in a sense and the contents are none of your business) architecture dependent, as most are.  Then, where does the FHS say they should go?  $PREFIX/lib

**Comment by x42** [comment]
The most interesting piece here is that `*.png` works without quotes in the find command :)

As @falkTX  mentioned most plugins do embed the data because it's a lot more convenient (no need to handle _file not found_, construct paths, etc etc). 

The other LV2 plugins that I know which have .png in the bundle dir are Harrison's XT-series.
